### ISSUE TITLE
Some problem during install

### ISSUE THREAD

**Issue by Chauncy-Fang** [dantaslab/resAnnotator#1]
Hey! I have tried to install resAnnotator and set the global environment using `**export PATH=$PATH:~/public/xrw/softwares/resAnnotator-master/1.1/**`, and then I try to operate resAnnotator by using "**`resAnnotator.py -h**`", but the screen show that "```
**Traceback (most recent call last):
  File "/home/vet/public/xrw/softwares/resAnnotator-master/1.1/bin/resAnnotator.py", line 3, in <module>
    from AnnotatorApp.settings import *
ModuleNotFoundError: No module named 'AnnotatorApp'**". 

Could you tell me how can I deal with it?
```

**Comment by Chauncy-Fang** [comment]
The issue above has been solve by move the module "AnnotatorAPP" from the origin file directory into site-package of python. But now the new problem appeared when start to run the program, the log was shown below:

`Started the ResAnnotator Pipeline v0.5.0
Traceback (most recent call last):
  File "./1.1/bin/resAnnotator.py", line 94, in <module>
    MainBase()
  File "./1.1/bin/resAnnotator.py", line 37, in __init__
    self.main_run()     
  File "./1.1/bin/resAnnotator.py", line 77, in main_run
    configuration = yaml.load(open(self.args['config_file']).read())
TypeError: load() missing 1 required positional argument: 'Loader'`

Coule you help me about how to deal with it ?
